### ISSUE TITLE
Add a license to the branding assets

### ISSUE THREAD

**Issue by Panquesito7** [devstrons/artwork#2]
I recommend using the [**CC BY-SA 4.0**](https://creativecommons.org/licenses/by-sa/4.0/) license. 🙂

**Comment by JOS-RE** [comment]
The [LICENSE](https://github.com/devstrons/artwork/blob/master/LICENSE) has been added to the assets. 
Thank you for bringing this up.

Looks like this issue can be closed now. 😄
